services:
  db:
    image: mariadb:lts
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  app:
    build: .
    environment:
      - NS_MARIADB_HOSTNAME=db
      - NS_MARIADB_PORT=3306
      - NS_MARIADB_USER=${MYSQL_USER}
      - NS_MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - NS_MARIADB_DATABASE=${MYSQL_DATABASE}
      - MAC_SECRET=${MAC_SECRET}
      - BOT_ID=${BOT_ID}
      - BOT_USER_ID=${BOT_USER_ID}
      - VERIFICATION_TOKEN=${VERIFICATION_TOKEN}
      - BOT_ACCESS_TOKEN=${BOT_ACCESS_TOKEN}
      - RASPI_SECRET=${RASPI_SECRET}
      - SEND_CHANNEL_ID=${SEND_CHANNEL_ID}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1323:1323"
  adminer:
    image: adminer:standalone
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
    ports:
      - "3001:8080"
